name: mi_workflow

on:
  push:
    branches:
      - "main"

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: download repository
        uses: actions/checkout@v3

      - name: prepare environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.1'
      
      - name: print go-version
        run: go version
      
      - name: Build
        run: go build -v .

      - name: unit test
        run: go test -v .


  build-push-image:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
