name: holamundo
on:
  push:
    branches:
      - "main"
jobs:
  holamundodenuevo:
    runs-on: ubuntu-latest
    steps:
      - name: imprimir
        run: echo "hola mundo"
      - name: clone repo
        run : git clone https://${{github.actor}}:${{github.token}}@github.com/ajmeza/workshop_gitAction.git
      - name: print
        run: ls -lha
  holamundoreusado:
    needs: [holamundodenuevo] 
    runs-on: ubuntu-latest
    steps:
      - name: prueba2
        uses: actions/checkout@v3
      - name: print
        run: ls -lha


        
