name: otraprueba
on:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: prueba2
        uses: actions/checkout@v3
      - name: prepare environment
        uses: actions/setup-go@v3
# https://github.com/marketplace/actions/setup-go-environment        
        with:
          go-version: '1.16.1'
      - name: version
        run: go version
      - name: Build
        run: go build -v .
      - name: unit test
        run: go test -v .
